Update Readme
logicalclocks/hopsworks pull request #1150
Opened 2022-08-09 09:43 UTC by MagicLex

Tried to keep it as clean and simple as possible.

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [ ] HOPSWORKS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-08-09 22:53 UTC, SirOibaf requested changes

2022-08-09 22:53 UTC, SirOibaf commented on README.md
> +
I think this sentence can be improved. I would state immediately that managed.hopsworks.ai integrates with the customer AWS/Azure/GCP environment.

2022-08-09 22:53 UTC, SirOibaf commented on README.md
> +If you wish to run Hopsworks on your Azure, AWS or GCP environnement, follow one of the following guides in our documentation:
typo in environment

2022-08-09 22:53 UTC, SirOibaf commented on README.md
> +[Hopsworks documentation](https://docs.hopsworks.ai) includes user-guides, Feature Store documentation, and an Administrator Guide. We also include concepts to help user navigates the abstractions an
user guides, feature store documentation and an administration guide.

2022-08-09 22:53 UTC, SirOibaf commented on README.md
> +Hopsworks API documentation is divided in 3 categories; Hopsworks API covers project level APIs, Feature Store API covers feature groups, training datasets and connectors and finally MLOPs API covers
covers feature groups, feature views and connectors. also type mlops with consistent capitalization.

2022-08-09 22:53 UTC, SirOibaf commented on README.md
> +Most of the tutorials require you to have at least an [app.hopsworks.ai](https://app.hopsworks.ai). You can explore the dedicated [https://github.com/logicalclocks/hopsworks-tutorials](https://github
at least an account on

2022-08-10 07:36 UTC, MagicLex reviewed
Updates and fixes

2022-08-10 07:40 UTC, SirOibaf commented on README.md
> +[Managed Hopsworks](https://managed.hopsworks.ai) is our platform for running Hopsworks and the Feature Store in the cloud and integrates direction with the customer AWS/Azure/GCP environment. It als
it alslo

2022-08-10 07:45 UTC, SirOibaf approved these changes

2022-08-10 07:45 UTC, merged