[HOPSWORKS-2460] reset password and delete user
logicalclocks/hopsworks pull request #849
Opened 2021-04-06 11:59 UTC by ErmiasG

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [ ] HOPSWORKS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-04-06 16:40 UTC, tkakantousis requested changes

2021-04-06 16:40 UTC, tkakantousis commented on hopsworks-api/src/main/java/io/hops/hopsworks/api/admin/UsersAdminResource.java
> +  @ApiOperation(value = "Delete a user specified by id.")
```suggestion
  @ApiOperation(value = "Delete a user specified by id. Only users without projects can be deleted.")
```

2021-04-07 07:07 UTC, ErmiasG commented
logicalclocks/hops-testing-ee/pull/318

2021-04-09 13:30 UTC, tkakantousis approved these changes

2021-04-09 13:31 UTC, merged