[HOPSWORKS-2633] Add Istio auth with API Keys
logicalclocks/hopsworks pull request #953
Opened 2021-11-05 10:20 UTC by javierdlrm

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [ ] HOPSWORKS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-11-05 14:43 UTC, tkakantousis requested changes
License fixes need to be applied on EE as well

2021-11-05 14:43 UTC, tkakantousis commented on hopsworks-common/src/main/java/io/hops/hopsworks/common/user/UserAccountHandler.java
> + * Copyright (C) 2021, Logical Clocks AB. All rights reserved
Needs community license

2021-11-05 14:43 UTC, tkakantousis commented on hopsworks-common/src/main/java/io/hops/hopsworks/common/user/security/apiKey/ApiKeyHandler.java
> + * Copyright (C) 2021, Logical Clocks AB. All rights reserved
Needs community license

2022-01-24 12:32 UTC, robzor92 approved these changes

2022-01-24 13:20 UTC, merged