job logs
logicalclocks/hopsworks pull request #986
Opened 2021-12-27 17:51 UTC by tkakantousis

## Make sure there is no duplicate PR for this issue

* **Please check if the PR meets the following requirements**
- [ ] Adds tests for the submitted changes (for bug fixes & features)
- [ ] Passes the tests
- [ ] HOPSWORKS JIRA issue has been opened for this PR
- [ ] All commits have been squashed down to a single commit

* **Post a link to the associated JIRA issue**

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-12-29 08:23 UTC, robzor92 requested changes

2021-12-29 08:23 UTC, robzor92 commented on docs/compute/jobs.md
> +In addition to te options available with the new job quickstart, from this menu you can set default arguments to be given as input to the job when
```suggestion
In addition to the options available with the new job quickstart, from this menu you can set default arguments to be given as input to the job when
```

2021-12-29 08:23 UTC, robzor92 commented on docs/compute/jobs.md
> +Once you have configured the alert channels, you can proceed by specifying alert `receivets` from the project's settings page.
```suggestion
Once you have configured the alert channels, you can proceed by specifying alert `receivers` from the project's settings page.
```

2021-12-29 09:00 UTC, robzor92 requested changes

2021-12-29 09:00 UTC, robzor92 commented on docs/compute/jobs.md
> +- Input the Hopworks project preferences and job details you wish to work on.
```suggestion
- Input the Hopsworks project preferences and job details you wish to work on.
```

2021-12-29 09:39 UTC, tkakantousis commented on docs/compute/jobs.md
> +provided in the Python section below.
fixed

2021-12-29 09:39 UTC, tkakantousis commented on docs/compute/jobs.md
> +``upload`` function of the ``dataset`` module of the ``hops`` Python library http://hops-py.logicalclocks.com
fixed

2021-12-30 10:31 UTC, robzor92 requested changes

2021-12-30 10:31 UTC, robzor92 commented on docs/compute/jobs.md
> +- **Run:** Uploads the program first to the HDFS path as specficied and runs job
```suggestion
- **Run:** Uploads the program first to the HDFS path as specified and runs job
```

2021-12-30 10:31 UTC, robzor92 commented on docs/compute/jupyter.md
> +`Open in Juptyer` under the `Recent notebooks` section of the dashboard. For example, in the image above you can see a
```suggestion
`Open in Jupyter` under the `Recent notebooks` section of the dashboard. For example, in the image above you can see a
```

2021-12-30 10:31 UTC, robzor92 commented on docs/compute/jupyter.md
> +Developing with Jupyter notebooks is provided as a service in Hopsworks as part the compute section of a project which you
```suggestion
Developing with Jupyter notebooks is provided as a service in Hopsworks as part of the compute section of a project which you 
```

2021-12-30 10:31 UTC, robzor92 commented on docs/compute/jupyter.md
> +If you would like to switch between configurations, you will to shut down Jupyter server first.
```suggestion
If you would like to switch between configurations, you will have to shut down the running Jupyter server first.
```

2021-12-30 10:31 UTC, robzor92 commented on docs/compute/jupyter.md
> +### Plotting with Pyspark Kernel
```suggestion
### Plotting with PySpark Kernel
```

2021-12-30 11:55 UTC, robzor92 approved these changes

2021-12-30 11:58 UTC, merged